services:
  nzip-server:
    container_name: nzip-server
    image: ghcr.io/nzip-team/nzip:latest
    # command: ['start.sh', '4'] # Uncomment to run in cluster mode
    ports:
      - '3000:3000'
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - SESSION_STORE=${SESSION_STORE}
      - REDIS_URL=redis://nzip-redis:6379
      - API_URL=${API_URL}
      - IMAGE_URL=${IMAGE_URL}
      - CONCURRENT_IMAGE_DOWNLOADS=${CONCURRENT_IMAGE_DOWNLOADS}
      - ANALYTICS=${ANALYTICS}
      - NODE_ENV=${NODE_ENV}
    restart: unless-stopped
    depends_on:
      - nzip-redis
  nzip-redis:
    container_name: nzip-redis
    image: redis:8-alpine
    expose:
      - '6379'
    command: ["redis-server", "--save", "900", "1", "--loglevel", "warning"]
    restart: unless-stopped
